/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;

export const idlService = IDL.Service({
  'getAllSubscribers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Time))],
      ['query'],
    ),
  'getSubscriber' : IDL.Func([IDL.Text], [Time], ['query']),
  'isSubscribed' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'joinNewsletter' : IDL.Func([IDL.Text], [], []),
  'unsubscribe' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  
  return IDL.Service({
    'getAllSubscribers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Time))],
        ['query'],
      ),
    'getSubscriber' : IDL.Func([IDL.Text], [Time], ['query']),
    'isSubscribed' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'joinNewsletter' : IDL.Func([IDL.Text], [], []),
    'unsubscribe' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };